# Generated by Django 5.1.1 on 2024-09-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_form_author_remove_post_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statistics', models.JSONField(default=dict)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='api.community')),
            ],
        ),
    ]
