# Generated by Django 5.1.1 on 2024-09-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='community',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='api.post'),
        ),
    ]
