# Generated by Django 5.1.1 on 2024-09-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_dashboard_community_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
