# Generated by Django 5.1.1 on 2024-09-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('plot_url', models.URLField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='api.post')),
            ],
        ),
    ]
