# Generated by Django 5.1.1 on 2024-09-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
