# Generated by Django 5.1.1 on 2024-09-15 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
    ]
