# Generated by Django 5.1.1 on 2024-09-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
