# Generated by Django 5.1.1 on 2024-09-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
