# Generated by Django 5.1.1 on 2024-09-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='author',
            new_name='admin',
        ),
    ]
